treatment_to_test = {
            'Acyclovir': None,
            'Ambisome': None,
            'Amikacin': 'AMIKACIN',
            'Ampicillin': 'AMPICILLIN',
            'Ampicillin/Sulbactam (Unasyn)': 'AMPICILLIN/SULBACTAM',
            'Atovaquone': None,
            'Azithromycin': None,
            'Aztreonam': None,
            'Bactrim (SMX/TMP)': 'TRIMETHOPRIM/SULFA',
            'Caspofungin': None,
            'Cefazolin': 'CEFAZOLIN',
            'Cefepime': 'CEFEPIME',
            'Ceftazidime': 'CEFTAZIDIME',
            'Ceftriaxone': 'CEFTRIAXONE',
            'Chloroquine': None,
            'Ciprofloxacin': 'CIPROFLOXACIN',
            'Clindamycin': 'CLINDAMYCIN',
            'Colistin': None,
            'Daptomycin': 'DAPTOMYCIN',
            'Doxycycline': 'TETRACYCLINE',
            'Erythromycin': 'ERYTHROMYCIN',
            'Ethambutol': None,
            'Fluconazole': None,
            'Foscarnet': None,
            'Gancyclovir': None,
            'Gentamicin': 'GENTAMICIN',
            'Imipenem/Cilastatin': 'IMIPENEM',
            'Isoniazid': None,
            'Keflex': 'CEFAZOLIN',  # Maybe check
            'Levofloxacin': 'LEVOFLOXACIN',
            'Linezolid': 'LINEZOLID',
            'Mefloquine': None,
            'Meropenem': 'MEROPENEM',
            'Metronidazole': None,
            'Micafungin': None,
            'Moxifloxacin': 'CIPROFLOXACIN',  # Check!
            'Nafcillin': 'PENICILLIN',  # Check!
            'Oxacillin': 'OXACILLIN',
            'Penicillin G potassium': 'PENICILLIN G',
            'Piperacillin': 'PIPERACILLIN',
            'Piperacillin/Tazobactam (Zosyn)': 'PIPERACILLIN/TAZO',
            'Pyrazinamide': None,
            'Quinine': None,
            'Ribavirin': None,
            'Rifampin': 'RIFAMPIN',
            'Tamiflu': None,
            'Tobramycin': 'TOBRAMYCIN',
            'Valgancyclovir': None,
            'Vancomycin': 'VANCOMYCIN',
            'Voriconazole': None
        }